### ISSUE TITLE
Input data not Byte type

### ISSUE THREAD

**Issue by wangchu92** [gvanas/KeccakCodePackage#15]
In the Keccak-readable-and-compact C code example, the parameter input type is Byte.

what if the input data is a 5-bit data as presented on the examples page at NIST’s Computer Security Resource Center web site: http://csrc.nist.gov/groups/ST/toolkit/examples.html.

Does that mean the C code example will not work as its padding function only deal with byte value?

**Comment by gvanas** [comment]
Hi,

In Keccak-readable-and-compact, the input string is the concatenation of:
- the input bytes as "input" parameter;
- from 0 to 7 trailing bits as "delimitedSuffix" parameter.

The delimited suffix is used to specify the suffixes used by the functions defined in FIPS 202, in which case it indeed leaves only a byte-level input to the user, e.g., as in FIPS202_SHAKE128().

Although it is not the main use case addressed by this implementation, the user can nevertheless play both with the input bytes and the trailing bits of the Keccak() function so as to be able to give any bit-level input string.

Kind regards,
Gilles
