### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by NicoHeijningen** [gvanas/KeccakCodePackage#16]
Hi,

I've tried to build the code package on different machines, yet all give me errors upon building and none output any binaries. On a Kali GNU/Linux 2.0 virtual machine I get the following:

> xsltproc -o bin/build/Makefile.expanded Build/ExpandProducts.xsl Makefile.build
> xsltproc -o bin/build/Makefile Build/ToGlobalMakefile.xsl bin/build/Makefile.expanded
> make: Warning: File 'bin/build/Makefile' has modification time 0.64 s in the future
> make: 'bin/build/Makefile' is up to date.
> make: warning:  Clock skew detected.  Your build may be incomplete.

A /bin/build folder is created which contains Makefile  Makefile.expanded.
When I try make in the /bin/build folder I get:

> make: *** No rule to make target 'Build/ToOneTarget.xsl', needed by 
> 'bin/build/ReadableCompactFIPS202.target'.
>  Stop.

I'm just hoping to build Ketje-Jr.

**Comment by NicoHeijningen** [comment]
Apparently one needs to copy the makefiles from /bin/build back to the root of the folder and run make again, then the binary is placed in /bin as you'd expect. Having to copy the build files to the root is not really expected behaviour in my opinion.

**Comment by gvanas** [comment]
Hi,

There should be no need to copy the makefiles back to the root.

Did you try `make KetjeJrReference` or something else?

Kind regards,
Gilles

**Comment by NicoHeijningen** [comment]
I just tried `<make>` under the assumption that that would generate all files.
`<make KetjeJrReference>` works I did not distill that from the readme.

Thanks for the quick reaction.

Would you maybe know of any single file high-level implementation of KetjeJr?

**Comment by gvanas** [comment]
I agree that the readme does not give enough information. Actually, we plan on improving that really soon.

No, sorry, we don't have a single-file implementation of KetjeJr, although I suppose this would be fairly easy to do. If you try `make KetjeJrReference.pack` you should get a `.tar.gz` pack with all the necessary files. That would be a way to get started.

**Comment by NicoHeijningen** [comment]
Thanks a lot!

I'll close this thread and will ask any further questions via your Noekeon email.
