### ISSUE TITLE
KangarooTwelve.org Repo

### ISSUE THREAD

**Issue by indolering** [gvanas/KeccakCodePackage#28]
Would it be possible to setup the KangarooTwelve.org domain as a Github static site?  I would like to do some advocacy for it.

**Comment by gvanas** [comment]
I created the repository [kangarootwelve.github.io](https://github.com/kangarootwelve/kangarootwelve.github.io) with minimal contents and with custom domain name [kangarootwelve.org](http://kangarootwelve.org). Does that work for you?
