### ISSUE TITLE
 Ethereum Keccak (Ethereum's web3.sha3())

### ISSUE THREAD

**Issue by digitaldonkey** [gvanas/KeccakCodePackage#33]
I just need a tool to calculate a Keccak256 hash from command line. Like 

```
keccak keccak256 "String to hash"
```

Somehow I think I'm in the right place here, but I can't get anything build. There are just too many options and instructions. Do you know any simplified howto?

**Comment by gvanas** [comment]
Just to make sure, what do you mean with "Keccak256"? Is is the pure Keccak[r=1088, c=512] as used in Ethereum (and as opposed to NIST's standardized SHA3-256 or SHAKE256)?

**Comment by gvanas** [comment]
I just added options to KeccakSum so that it can do what you want.

To make:
`make generic64/KeccakSum`

To use, assuming you want the pure Keccak[r=1088, c=512] as in Ethereum:
`KeccakSum --ethereum --string "testing"`

**Comment by digitaldonkey** [comment]
Finally I also got things compiled. Summing up: 

```
make generic64/KeccakSum
bin/generic64/KeccakSum KeccakSum --ethereum --string ""
f5wrpOiPgn1hYEVQdgWFPtc7gJP277yI6xpurPpm7yY8  KeccakSum
c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470  ""
```

I don't understand the line 

`f5wrpOiPgn1hYEVQdgWFPtc7gJP277yI6xpurPpm7yY8  KeccakSum`

but "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470" is the corresponding Ethereum hash for an empty string (web3.sha3()). 

Is there a parameter which only returns the value for easier return values? Or a manpage which I couldn't find.

**Comment by gvanas** [comment]
There is one `KeccakSum` too much on your input. (`f5w…` is the SHAKE128 digest of the file `KeccakSum` in base64 format.)

Sorry, we didn't write a man page for KeccakSum. I put it on our to-do list (unless someone would like to do it).

**Comment by digitaldonkey** [comment]
Updated my previous comment. Thank you.

**Comment by gvanas** [comment]
Thanks. I think I can close this issue now.
