### ISSUE TITLE
Can't call KCP from thumb-2 programs

### ISSUE THREAD

**Issue by bitwiseshiftleft** [gvanas/KeccakCodePackage#35]
Hello all,

I'm attempting to use KCP on ARM.  I've compiled the ARMv7A target, and I can call it from ARM code but not from Thumb-2 code.  As soon as it enters an asm routine, it crashes.

Is there some way to enable Thumb-2 functions to call the KCP?

**Comment by tkchia** [comment]
Hello bitwiseshiftleft, hello Keccak maintainers,

I encountered the same problem trying to compile and run a test program, like so:
```
CC=arm-linux-gnueabi-gcc \
CFLAGS='-march=armv7-a -mfpu=neon -mthumb -mabi=aapcs' \
make SHA3-384_SelfTest/optimized1600ARMv7A
```

I managed to fix it by labelling the globally visible assembly language routines as functions using `.type`.  E.g.
```
.global   KeccakP1600_Initialize
.type     KeccakP1600_Initialize, %function
KeccakP1600_Initialize: ...
```

This way, the linker will produce interworking call instructions in Thumb callers that invoke the routines (e.g. `blx KeccakP1600_Initialize` and not `bl KeccakP1600_Initialize`), which will correctly transition from Thumb mode to ARM mode.

I will file a pull request for the fix if necessary.  (Unfortunately the above is only for the GNU assembler source files (`*-gcc.s`), I am not sure if the `*-armcc.s` source files need a similar fix.)

Thank you!

**Comment by bitwiseshiftleft** [comment]
Yes, this worked for me.  Attached is a diff which fixes the *-gcc.s files.  I also didn't try to fix the *-armcc.s files.

[types.diff.txt](https://github.com/gvanas/KeccakCodePackage/files/1350735/types.diff.txt)

**Comment by gvanas** [comment]
Hello bitwiseshiftleft, hello tkchia,

Sorry for the delay, I was on holiday. I will check with Ronny, who wrote most of the ARM code in the KCP.

Kind regards,
Gilles

**Comment by gvanas** [comment]
I just applied and pushed your fix. Thanks!
