### ISSUE TITLE
Rust k12 implementation

### ISSUE THREAD

**Issue by dhardy** [gvanas/KeccakCodePackage#36]
Just thought I'd say I implemented and tested k12 in Rust. You can copy the code back here if you like; it's CC0; it may also get incorporated into [this repo](https://github.com/RustCrypto/hashes).

My code is not well optimised or a very "rustic style" since it was a lazy port of the Python code, so don't consider it at all indicative of Rust performance! That said it still appears to be a lot faster than the Python version.

https://github.com/dhardy/hash-bench/blob/master/src/k12.rs

**Comment by gvanas** [comment]
Sure. I just reorganized the `Standalone/` folder. Can you put your file in `Standalone/KangarooTwelve/Rust/` and do a pull request? Thanks!

**Comment by gvanas** [comment]
PS: Note that I can also add the file myself, but since there is nothing in it that credits you, I thought that a pull request would at least leave your name in the commit. Just let me know.

**Comment by gvanas** [comment]
Just merged, thanks!
