### ISSUE TITLE
KeccakP1600 Optimized64 big endian bug

### ISSUE THREAD

**Issue by sebastinas** [gvanas/KeccakCodePackage#42]
While debugging test failures of [Picnic](https://github.com/IAIK/Picnic) on s390x, I noticed that the Optimized64 implementation of KeccakP1600 produces different output based on the endianess of the architecture. Consider the following test program, which calls SHAKE256 for 32 byte outputs for various input lengths:

```c
#include "KeccakHash.h"
#include "SimpleFIPS202.h"
#include <stdio.h>

int main() {
  for (unsigned int j = 1; j < 256; ++j) {
    Keccak_HashInstance ctx;
    Keccak_HashInitialize_SHAKE256(&ctx);

    // j byte input
    unsigned char input[256];
    for (unsigned int i = 0; i != j; ++i) {
      input[i] = i;
    }

    Keccak_HashUpdate(&ctx, input, j * 8);
    Keccak_HashFinal(&ctx, NULL);

    // 32 byte output
    unsigned char output[32];
    Keccak_HashSqueeze(&ctx, output, sizeof(output) * 8);
    for (unsigned int i = 0; i != sizeof(output); ++i) {
      printf("%02x ", output[i]);
    }
    printf("\n");

    SHAKE256(output, sizeof(output), input, j);
    for (unsigned int i = 0; i != sizeof(output); ++i) {
      printf("%02x ", output[i]);
    }
    printf("\n");
  }
  return 0;
}
```

Using the code from `make FIPS202-opt64.pack` the test program produces the following output on x86-64 https://gist.github.com/sebastinas/e4a7ac81629d716c0b8c2599c25e25dc#file-output-ref-and-opt64-on-x86-64. The reference implementation (```<target name="FIPS202-ref" inherits="FIPS202 reference1600"/>```) implementation agrees with the output on both x86-64 and s390x. However, opt64 on s390x produces different output: https://gist.github.com/sebastinas/e4a7ac81629d716c0b8c2599c25e25dc#file-output-opt64-s390x.

Please let me know if I can help debugging and fixing this issue.

**Comment by gvanas** [comment]
Hello Sebastian,

indeed, this optimized64 target should work on big-endian platforms, as the code outside of the little endian-specific parts should be endian-neutral.

As I don't have access to a big-endian platform, your collaboration would indeed be very useful.

I would suggest to start with the unit tests: `make generic64/KeccakTests`, then `bin/generic64/KeccakTests -p`, and see where it breaks.

Kind regards,
Gilles

**Comment by gvanas** [comment]
OK, thanks. So it seems that the bug is either in `KeccakP1600_AddByte()` or `KeccakP1600_ExtractBytes()`. Could you dump the contents of the variables state and buffer before the failing assertion? (If easier, we could continue by phone…)

**Comment by sebastinas** [comment]
```
(gdb) p *state@200 
$12 = "\000\001\002\003\004\005\006\a\b\t\n\v\f\r\016\017\020\021\022\023\024\025\026\027\030\031\032\033\034\035\036\037 !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\177\200\201\202\203\204\205\206\207\210\211\212\213\214\215\216\217\220\221\222\223\224\225\226\227\230\231\232\233\234\235\236\237\240\241\242\243\244\245\246\247\250\251\252\253\254\255\256\257\260\261\262\263\264\265\266\267\270\271\272\273\274\275\276\277\300\301\302\303\304\305\306\307"
(gdb) p *buffer@200
$13 = "\a\006\005\004\003\002\001\000\017\016\r\f\v\n\t\b\027\026\025\024\023\022\021\020\037\036\035\034\033\032\031\030'&%$#\"! /.-,+*)(76543210?>=<;:98GFEDCBA@ONMLKJIHWVUTSRQP_^]\\[ZYXgfedcba`onmlkjihwvutsrqp\177~}|{zyx\207\206\205\204\203\202\201\200\217\216\215\214\213\212\211\210\227\226\225\224\223\222\221\220\237\236\235\234\233\232\231\230\247\246\245\244\243\242\241\240\257\256\255\254\253\252\251\250\267\266\265\264\263\262\261\260\277\276\275\274\273\272\271\270\307\306\305\304\303\302\301\300"
```

**Comment by gvanas** [comment]
The contents of `*state` does not look correct. Interpreted as an array of 64-bit words, it should contain `0x0706050403020100`, independently of the endianness. Hence, on a big-endian platform, the bytes should start from `0x07`.

This suggests that `KeccakP1600_AddByte()` is incorrect, but it is not clear to me how at this point.

**Comment by gvanas** [comment]
Would it be possible that the conditional compilation incorrectly results in the little endian-specific code being compiled? One way to check this would be to put an `#error` in the `KeccakP1600_AddByte()` function on line 182.

Another thing: @WandyLau also worked on a s390. There were missing pieces that we fixed in the meantime, but he did not complain about something not working correctly, see [this issue](https://github.com/gvanas/KeccakCodePackage/issues/38).

**Comment by sebastinas** [comment]
If I put an #error there, it fails, so it picks the big endian specific variant of `KeccakP1600_AddByte()`.

**Comment by gvanas** [comment]
Thanks for your fix!
